apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagepullsecret-serviceaccount-patcher
  namespace: kube-system
  labels:
    app.kubernetes.io/name: imagepullsecret-serviceaccount-patcher
    app.kubernetes.io/instance: patcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: imagepullsecret-serviceaccount-patcher
      app.kubernetes.io/instance: patcher
  template:
    metadata:
      labels:
        app.kubernetes.io/name: imagepullsecret-serviceaccount-patcher
        app.kubernetes.io/instance: patcher
    spec:
      serviceAccountName: imagepullsecret-serviceaccount-patcher
      securityContext: {}
      containers:
      - name: imagepullsecret-serviceaccount-patcher
        securityContext: {}
        image: neutryno/imagepullsecret-serviceaccount-patcher:latest
        imagePullPolicy: IfNotPresent
        args: []
        env:
        - name: REGISTRY_SECRET_NAMES
          value: "" # This must be filled in for ips-sa-p to function; see README
        resources: {}
