apiVersion: v1
kind: ServiceAccount
metadata:
  name: imagepullsecret-serviceaccount-patcher
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imagepullsecret-serviceaccount-patcher
rules:
- apiGroups: [ "" ]
  resources: [ "namespaces" ]
  verbs: [ "get", "watch", "list" ]
- apiGroups: [""] # "" indicates the core API group
  resources: ["serviceaccounts"]
  verbs: ["get", "watch", "list", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: imagepullsecret-serviceaccount-patcher
roleRef:
  kind: ClusterRole
  name: imagepullsecret-serviceaccount-patcher
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: imagepullsecret-serviceaccount-patcher
  namespace: kube-system
