apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
  - kustomizeconfig/nameRef.yaml

resources:
  - https://raw.githubusercontent.com/mittwald/kubernetes-replicator/v2.10.0/deploy/rbac.yaml
  - https://raw.githubusercontent.com/mittwald/kubernetes-replicator/v2.10.0/deploy/deployment.yaml
  - https://raw.githubusercontent.com/Blaimi/imagepullsecret-serviceaccount-patcher/master/deployment/rbac.yaml
  - https://raw.githubusercontent.com/Blaimi/imagepullsecret-serviceaccount-patcher/master/deployment/deployment.yaml

secretGenerator:
  - name: custom-pull-secret
    namespace: kube-system
    files:
      - .dockerconfigjson
    type: kubernetes.io/dockerconfigjson
    options:
      annotations:
        replicator.v1.mittwald.de/replicate-to: ".*"

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/0/value
        value: custom-pull-secret
    target:
      group: apps
      version: v1
      kind: Deployment
      name: imagepullsecret-serviceaccount-patcher
      namespace: kube-system
