name: image-build
on: push

env:
  REGISTRY: ghcr.io

jobs:
  image-name:
    name: Image Name
    runs-on: ubuntu-latest
    outputs:
      image-name: ${{ steps.image-name.outputs.image-name }}
    steps:
      - name: lowercase github.repository
        id: image-name
        run: |
          echo "image-name=${GITHUB_REPOSITORY@L}" >> ${GITHUB_OUTPUT}
  build-and-push-image:
    runs-on: ubuntu-latest
    needs: image-name
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ needs.image-name.outputs.image-name }}
          tags: |
            type=ref,event=branch
            type=sha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          file: |
            ./Dockerfile
          context: .
          push: true
          platforms: |
            linux/arm64
            linux/amd64
          cache-from: |
            type=registry,ref=${{ env.REGISTRY }}/${{ needs.image-name.outputs.image-name }}:buildcache
          cache-to: |
            type=registry,ref=${{ env.REGISTRY }}/${{ needs.image-name.outputs.image-name }}:buildcache,mode=max
          tags: |
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
